default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: supply_development
  host: localhost
  username: postgres
  password: MyPassword

test:
  <<: *default
  database: supply_test
  username: postgres
  password: MyPassword

production:
  <<: *default
  database: supply_production
  username: postgres
  password: <%= ENV["SUPPLY_DATABASE_PASSWORD"] %>
